version: '3'
services:
  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=senha123
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=mybucket
    networks:
      - monitoring_network

  # grafana:
    # image: grafana/grafana:latest
    # container_name: grafana
    # ports:
      # - "3000:3000"
    # volumes:
      # - grafana-data:/var/lib/grafana
    # environment:
      # - GF_SECURITY_ADMIN_USER=admin
      # - GF_SECURITY_ADMIN_PASSWORD=senha123
    # depends_on:
      # - influxdb
    # networks:
      # - monitoring_network

volumes:
  influxdb-data:
  # grafana-data:

networks:
  monitoring_network: